# Generated by Django 5.0.6 on 2024-06-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rmovie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rmovie',
            table='rmovies',
        ),
    ]
