# Generated by Django 5.0.6 on 2024-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_rmovie_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.TextField()),
                ('starring', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'umovies',
            },
        ),
    ]
