# Generated by Django 5.0.6 on 2024-06-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_umovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvr_name', models.CharField(max_length=150)),
                ('show_1', models.CharField(max_length=150)),
                ('show_2', models.CharField(max_length=150)),
                ('show_3', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pvr_details',
            },
        ),
        migrations.AlterField(
            model_name='rmovie',
            name='director',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rmovie',
            name='genre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rmovie',
            name='starring',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rmovie',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='umovie',
            name='director',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='umovie',
            name='genre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='umovie',
            name='release_date',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='umovie',
            name='starring',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='umovie',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
