# Generated by Django 5.0.6 on 2024-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pvr_alter_rmovie_director_alter_rmovie_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=255)),
                ('pvr', models.CharField(max_length=255)),
                ('show_time', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('seats', models.TextField()),
            ],
        ),
    ]
