# Generated by Django 5.0.6 on 2024-06-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
