# Generated by Django 5.0.6 on 2024-06-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
